-- 1. Table: categories
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'pemasukan' or 'pengeluaran'
  emoji TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS untuk categories
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for users based on user_id" ON categories FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON categories FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON categories FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON categories FOR DELETE USING (auth.uid() = user_id);

-- Default data untuk kategori (Opsional, dijalankan di trigger atau insert manual)
-- Karena `user_id` diperlukan, kategori default biasanya di set per user, atau bisa dibuat tanpa RLS bila public.


-- 2. Table: transactions
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'pemasukan' or 'pengeluaran'
  amount NUMERIC NOT NULL,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  method TEXT DEFAULT 'tunai',
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS untuk transactions
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for users based on user_id" ON transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON transactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON transactions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON transactions FOR DELETE USING (auth.uid() = user_id);


-- 3. Table: capital_records
CREATE TABLE capital_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  buy_price NUMERIC NOT NULL DEFAULT 0,
  sell_price NUMERIC NOT NULL DEFAULT 0,
  quantity NUMERIC NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS untuk capital_records
ALTER TABLE capital_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for users based on user_id" ON capital_records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON capital_records FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON capital_records FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON capital_records FOR DELETE USING (auth.uid() = user_id);


-- 4. Table: payment_methods
CREATE TABLE payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  emoji TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, name)
);

-- RLS untuk payment_methods
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for users based on user_id" ON payment_methods FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON payment_methods FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON payment_methods FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON payment_methods FOR DELETE USING (auth.uid() = user_id);

