-- Migration: Add suppliers, customer_invoices, and update capital_records (V2)

-- 1. Create suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  contact_info TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for suppliers
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for users based on user_id" ON suppliers FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON suppliers FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON suppliers FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON suppliers FOR DELETE USING (auth.uid() = user_id);

-- Drop old supplier_invoices if existed
DROP TABLE IF EXISTS supplier_invoices CASCADE;

-- 2. Create customer_invoices table (Nota Penjualan Pelanggan)
CREATE TABLE IF NOT EXISTS customer_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  invoice_number TEXT NOT NULL,
  date DATE NOT NULL,
  status TEXT NOT NULL, -- 'lunas', 'dp', 'belum_lunas'
  total_amount NUMERIC NOT NULL DEFAULT 0,
  paid_amount NUMERIC NOT NULL DEFAULT 0,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for customer_invoices
ALTER TABLE customer_invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for users based on user_id" ON customer_invoices FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON customer_invoices FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON customer_invoices FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON customer_invoices FOR DELETE USING (auth.uid() = user_id);

-- 3. Create capital_records_v2 table (terpisah dari capital_records V1)
CREATE TABLE IF NOT EXISTS capital_records_v2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  buy_price NUMERIC NOT NULL DEFAULT 0,
  sell_price NUMERIC NOT NULL DEFAULT 0,
  quantity NUMERIC NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  note TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  customer_invoice_id BIGINT REFERENCES customer_invoices(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for capital_records_v2
ALTER TABLE capital_records_v2 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for users based on user_id" ON capital_records_v2 FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON capital_records_v2 FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON capital_records_v2 FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON capital_records_v2 FOR DELETE USING (auth.uid() = user_id);

-- 4. Create supplier_payments table
CREATE TABLE IF NOT EXISTS supplier_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
  payment_method_id BIGINT REFERENCES payment_methods(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  payment_date DATE NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for supplier_payments
ALTER TABLE supplier_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for users based on user_id" ON supplier_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON supplier_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON supplier_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON supplier_payments FOR DELETE USING (auth.uid() = user_id);

-- 5. Create customer_payments table (Log Pembayaran dari Pelanggan V2)
DROP TABLE IF EXISTS customer_payments CASCADE;

CREATE TABLE IF NOT EXISTS customer_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_invoice_id BIGINT NOT NULL REFERENCES customer_invoices(id) ON DELETE CASCADE,
  payment_method_id BIGINT REFERENCES payment_methods(id) ON DELETE SET NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  payment_date DATE NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for customer_payments
ALTER TABLE customer_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for users based on user_id" ON customer_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for authenticated users only" ON customer_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Enable update for users based on user_id" ON customer_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Enable delete for users based on user_id" ON customer_payments FOR DELETE USING (auth.uid() = user_id);
